[versions]
buildTools = "36.1.0"

minSdk = "23"

compileSdk = "36"
compileSdkMinor = "1"

compileSdkExtension = "20"

targetSdk = "36"

agp = "8.13.0"

androidxActivity = "1.11.0"
androidxAppcompat = "1.7.1"
androidxConstraintlayout = "2.2.1"

kotlin = "2.2.21"

material = "1.13.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }

androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
